/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;
import Form.History;
import Form.Home;
import Form.Menu;
import Form.Wallet;
import java.awt.Color;
/**
 *
 * @author mac
 */
public class Mainn extends javax.swing.JFrame {

    Color DefaultColor,ClickedColor,BackColor, Har;
    public Mainn() {
        initComponents();
        DefaultColor = new Color (140,140,140);
        ClickedColor = new Color (255,255,255);
        BackColor = new Color (70,70,70);
        Har = new Color (35,35,35);
        
        MenuWord.setForeground(DefaultColor);
        HomeWord.setForeground(DefaultColor);
        RatingWord.setForeground(DefaultColor);
        HistoryWord.setForeground(DefaultColor);
        
        Menu.setBackground(Har);
        Home.setBackground(Har);
        Wallet.setBackground(Har);
        History.setBackground(Har);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        HomeWord = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        MenuWord = new javax.swing.JLabel();
        Wallet = new javax.swing.JPanel();
        RatingWord = new javax.swing.JLabel();
        History = new javax.swing.JPanel();
        HistoryWord = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        InfoPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(244, 244, 244));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(35, 35, 35));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home.setBackground(new java.awt.Color(35, 35, 35));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HomeMousePressed(evt);
            }
        });

        HomeWord.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        HomeWord.setForeground(new java.awt.Color(255, 255, 255));
        HomeWord.setText("Home");

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(HomeWord)
                .addGap(47, 47, 47))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addComponent(HomeWord, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 140, 40));

        Menu.setBackground(new java.awt.Color(35, 35, 35));
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuMousePressed(evt);
            }
        });

        MenuWord.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        MenuWord.setForeground(new java.awt.Color(140, 140, 140));
        MenuWord.setText("Menu");

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(MenuWord)
                .addGap(50, 50, 50))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addComponent(MenuWord, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 140, 40));

        Wallet.setBackground(new java.awt.Color(35, 35, 35));
        Wallet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                WalletMousePressed(evt);
            }
        });

        RatingWord.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        RatingWord.setForeground(new java.awt.Color(140, 140, 140));
        RatingWord.setText("Wallet");

        javax.swing.GroupLayout WalletLayout = new javax.swing.GroupLayout(Wallet);
        Wallet.setLayout(WalletLayout);
        WalletLayout.setHorizontalGroup(
            WalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WalletLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(RatingWord, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        WalletLayout.setVerticalGroup(
            WalletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RatingWord, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.add(Wallet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 140, 40));

        History.setBackground(new java.awt.Color(35, 35, 35));
        History.setForeground(new java.awt.Color(255, 255, 255));
        History.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HistoryMousePressed(evt);
            }
        });

        HistoryWord.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        HistoryWord.setForeground(new java.awt.Color(140, 140, 140));
        HistoryWord.setText("  History");

        javax.swing.GroupLayout HistoryLayout = new javax.swing.GroupLayout(History);
        History.setLayout(HistoryLayout);
        HistoryLayout.setHorizontalGroup(
            HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HistoryLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(HistoryWord, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        HistoryLayout.setVerticalGroup(
            HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HistoryWord, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.add(History, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 140, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("@ MyBuuz");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 700));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/icons8-user-menu-male-48(1).png"))); // NOI18N

        Name.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 150, 70));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 1070, 100));

        InfoPanel.setLayout(new java.awt.BorderLayout());
        jPanel1.add(InfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 1070, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMousePressed
        Menu.setBackground(Har);
        Home.setBackground(BackColor);
        MenuWord.setForeground(DefaultColor);
        RatingWord.setForeground(DefaultColor);
        HistoryWord.setForeground(DefaultColor);
        HomeWord.setForeground(ClickedColor);
        Wallet.setBackground(Har);
        History.setBackground(Har);
        Home home1 = new Home();
        InfoPanel.removeAll();
        InfoPanel.add(home1).setVisible(true);
    }//GEN-LAST:event_HomeMousePressed

    private void MenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMousePressed
        Menu.setBackground(BackColor);
        Home.setBackground(Har);
        MenuWord.setForeground(ClickedColor);
        Wallet.setBackground(Har);
        History.setBackground(Har);
        HomeWord.setForeground(DefaultColor);
        RatingWord.setForeground(DefaultColor);
        HistoryWord.setForeground(DefaultColor);
        Menu menu1 = new Menu();
        InfoPanel.removeAll();
        InfoPanel.add(menu1).setVisible(true);
    }//GEN-LAST:event_MenuMousePressed

    private void WalletMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WalletMousePressed
        Menu.setBackground(Har);
        Home.setBackground(Har);
        RatingWord.setForeground(ClickedColor);
        Wallet.setBackground(BackColor);
        History.setBackground(Har);
        MenuWord.setForeground(DefaultColor);
        HomeWord.setForeground(DefaultColor);
        HistoryWord.setForeground(DefaultColor);
        Wallet wallet1 = new Wallet();
        InfoPanel.removeAll();
        InfoPanel.add(wallet1).setVisible(true);
    }//GEN-LAST:event_WalletMousePressed

    private void HistoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoryMousePressed
        Menu.setBackground(Har);
        Home.setBackground(Har);
        HistoryWord.setForeground(ClickedColor);
        Wallet.setBackground(Har);
        History.setBackground(BackColor);
        MenuWord.setForeground(DefaultColor);
        HomeWord.setForeground(DefaultColor);
        RatingWord.setForeground(DefaultColor);
        History history1 = new History();
        InfoPanel.removeAll();
        InfoPanel.add(history1).setVisible(true);
        
    }//GEN-LAST:event_HistoryMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel History;
    private javax.swing.JLabel HistoryWord;
    private javax.swing.JPanel Home;
    private javax.swing.JLabel HomeWord;
    private javax.swing.JPanel InfoPanel;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel MenuWord;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel RatingWord;
    private javax.swing.JPanel Wallet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
