/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import java.awt.Color;

/**
 *
 * @author mac
 */
public class Mainn extends javax.swing.JFrame {

    Color DefaultColor,ClickedColor;
    public Mainn() {
        initComponents();
        DefaultColor = new Color (140,140,140);
        ClickedColor = new Color (255,255,255);
        
        MenuWord.setForeground(DefaultColor);
        HomeWord.setForeground(DefaultColor);
        RatingWord.setForeground(DefaultColor);
        HistoryWord.setForeground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        HomeWord = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        MenuWord = new javax.swing.JLabel();
        Rating = new javax.swing.JPanel();
        RatingWord = new javax.swing.JLabel();
        History = new javax.swing.JPanel();
        HistoryWord = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(35, 35, 35));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home.setBackground(new java.awt.Color(35, 35, 35));

        HomeWord.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        HomeWord.setForeground(new java.awt.Color(255, 255, 255));
        HomeWord.setText("Home");
        HomeWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeWordMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(HomeWord)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addComponent(HomeWord, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 140, 40));

        Menu.setBackground(new java.awt.Color(35, 35, 35));

        MenuWord.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        MenuWord.setForeground(new java.awt.Color(140, 140, 140));
        MenuWord.setText("Menu");
        MenuWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuWordMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(MenuWord)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addComponent(MenuWord, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 140, 40));

        Rating.setBackground(new java.awt.Color(35, 35, 35));

        RatingWord.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        RatingWord.setForeground(new java.awt.Color(140, 140, 140));
        RatingWord.setText("Rating");
        RatingWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RatingWordMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout RatingLayout = new javax.swing.GroupLayout(Rating);
        Rating.setLayout(RatingLayout);
        RatingLayout.setHorizontalGroup(
            RatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RatingLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(RatingWord)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        RatingLayout.setVerticalGroup(
            RatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RatingLayout.createSequentialGroup()
                .addComponent(RatingWord, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(Rating, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 140, 40));

        History.setBackground(new java.awt.Color(35, 35, 35));
        History.setForeground(new java.awt.Color(255, 255, 255));

        HistoryWord.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        HistoryWord.setForeground(new java.awt.Color(140, 140, 140));
        HistoryWord.setText("History");
        HistoryWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HistoryWordMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout HistoryLayout = new javax.swing.GroupLayout(History);
        History.setLayout(HistoryLayout);
        HistoryLayout.setHorizontalGroup(
            HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistoryLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(HistoryWord)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        HistoryLayout.setVerticalGroup(
            HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistoryLayout.createSequentialGroup()
                .addComponent(HistoryWord, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(History, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 140, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 135, 700));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 1080, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuWordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuWordMouseEntered
        MenuWord.setForeground(ClickedColor);
        HomeWord.setForeground(DefaultColor);
        RatingWord.setForeground(DefaultColor);
        HistoryWord.setForeground(DefaultColor);
    }//GEN-LAST:event_MenuWordMouseEntered

    private void HomeWordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeWordMouseEntered
        MenuWord.setForeground(DefaultColor);
        HomeWord.setForeground(ClickedColor);
        RatingWord.setForeground(DefaultColor);
        HistoryWord.setForeground(DefaultColor);
    }//GEN-LAST:event_HomeWordMouseEntered

    private void RatingWordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RatingWordMouseEntered
        MenuWord.setForeground(DefaultColor);
        HomeWord.setForeground(DefaultColor);
        RatingWord.setForeground(ClickedColor);
        HistoryWord.setForeground(DefaultColor);
    }//GEN-LAST:event_RatingWordMouseEntered

    private void HistoryWordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoryWordMouseEntered
        MenuWord.setForeground(DefaultColor);
        HomeWord.setForeground(DefaultColor);
        RatingWord.setForeground(DefaultColor);
        HistoryWord.setForeground(ClickedColor);
    }//GEN-LAST:event_HistoryWordMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel History;
    private javax.swing.JLabel HistoryWord;
    private javax.swing.JPanel Home;
    private javax.swing.JLabel HomeWord;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel MenuWord;
    private javax.swing.JPanel Rating;
    private javax.swing.JLabel RatingWord;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
